# Copyright © Patrick Stoeckle none - none
#
# Licensed under the Apache License License 2.0
#
# Authors: 
#
# SPDX-FileCopyrightText: none Patrick Stoeckle
#
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff – Lint
        entry: ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: Ruff – Format code
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: mypy
        name: mypy – Check typing
        entry: mypy
        language: system
        require_serial: true
        types: [python]
