# Copyright © Patrick Stoeckle 2025 - 2025
#
# Licensed under the Apache License License 2.0
#
# Authors: Patrick Stoeckle
#
# SPDX-FileCopyrightText: 2025 Patrick Stoeckle
#
# SPDX-License-Identifier: Apache-2.0

[NEW_SCRIPT]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[JINJA]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[MARKDOWN]
firstLine = '<!--'
endLine = "-->\n"
beforeEachLine = ''
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '\s*<!--.*$'
lastLineDetectionPattern = '\s*-->.*$'
