# Copyright © Patrick Stoeckle 2022 - 2025
#
# Licensed under the Apache License License 2.0
#
# Authors: Patrick Stoeckle, Patrick Stöckle
#
# SPDX-FileCopyrightText: 2022 Patrick Stoeckle
#
# SPDX-License-Identifier: Apache-2.0

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build package
        run: uv build --quiet
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
