# Copyright © Patrick Stoeckle 2022 - 2022
#
# Licensed under the Apache License License 2.0
#
# Authors: Patrick Stöckle
#
# SPDX-FileCopyrightText: 2022 Patrick Stoeckle
#
# SPDX-License-Identifier: Apache-2.0

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    container:
      image: tumi4/python-3.9-bullseye-poetry-1.2.1
      options: --user 1001
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: poetry build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
