# Copyright © Patrick Stoeckle 2022 - 2025
#
# Licensed under the Apache License License 2.0
#
# Authors: Patrick Stoeckle, Patrick Stöckle
#
# SPDX-FileCopyrightText: 2022 Patrick Stoeckle
#
# SPDX-License-Identifier: Apache-2.0

name: Python tests

on:
  push:
    paths:
      - ".github/workflows/python-test.yml"
      - "pyproject.toml"
      - "sharelatex_versioning/**/*.py"

permissions:
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv sync
      - name: Lint with ruff
        run: |
          uv run -- ruf check
      - name: Lint with mypy
        run: |
          uv run -- mypy --cobertura-xml-report=. --junit-xml=mypy.xml --pretty ./sharelatex_versioning
      - name: Archive typing coverage results
        uses: actions/upload-artifact@v3
        with:
          name: typing-coverage-report
          path: cobertura.xml
        if: ${{ always() }}
      - name: Test with pytest
        run: |
          uv run -- pytest --junitxml report.xml --cov=sharelatex_versioning --cov-report xml ./tests
      - name: Archive test coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: coverage.xml
        if: ${{ always() }}
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          indicators: true
          output: both
          thresholds: "60 80"
